# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hi, I'm Saent
email: support@saent.com
description: Saent helps you to focus, be more productive and build better work habits.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://start.saent.com/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
